hpatches:
    dataset_dir: /mnt/sgnfsdata/tolo-03-97/willwu/SAMFeat/evaluation_hpatch/hpatches_sequences/hpatches-sequences-release
    resize: false
    grayscale: false

model:
    name: SAMFeat
    backbone: network.SAMFeat
    detection_threshold: 0.9 # used to be 0.9
    nms_dist: 4
    nms_radius: 4
    border_remove: 4
    weight_path: /mnt/sgnfsdata/tolo-03-97/willwu/SAMFeat/
    ckpt_name: ckpt #mtl_mtldesc
    weights_id: model_29.pt
    desc_dim: 128

keys: keypoints,descriptors,shape
output_type: normal #benchmark #


